// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a mock supabase client if URL/key are not configured
const createMockSupabase = () => ({
  from: (table: string) => ({
    select: (columns?: string) => ({
      order: (column: string, options?: { ascending?: boolean }) => Promise.resolve({ data: [], error: null }),
      eq: (column: string, value: any) => ({
        single: () => Promise.resolve({ data: null, error: null }),
        select: () => Promise.resolve({ data: [], error: null }),
      }),
      single: () => Promise.resolve({ data: null, error: null }),
    }),
    insert: (values: any) => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
    update: (values: any) => ({
      eq: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
      select: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
    }),
    delete: () => ({
      eq: () => Promise.resolve({ error: { message: 'Supabase not configured' } }),
    }),
  }),
});

let supabaseInstance: any;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  try {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (error) {
    console.warn('Failed to initialize Supabase client, using mock:', error);
    supabaseInstance = createMockSupabase();
  }
} else {
  // Create a mock client that returns empty results
  console.warn('Supabase not configured. Using localStorage fallback.');
  supabaseInstance = createMockSupabase();
}

export const supabase = supabaseInstance;
